### ISSUE TITLE
Would you consider publishing this to JSR?

### ISSUE THREAD

**Issue by sgwilym** [korkje/fifo#3]
I'm in the process of migrating some packages to [JSR](https://jsr.io), several of which depend on this module. At the moment I have to vendor this module as JSR only does not allow HTTP dependencies, only NPM / JSR dependencies. I _think_ it would only be a matter of adding three fields to `deno.json` and publishing. As a bonus this module would also be available to Node and Bun users.

**Comment by korkje** [comment]
Good suggestion 👍 I have a bunch of Deno packages both personally and at work that I've been thinking about publishing to JSR, I just haven't landed on my preferred setup for a pipeline yet. I'll keep this issue open until it is done, might look into it sometime the coming week.

**Comment by korkje** [comment]
FIFO is now [onJSR](https://jsr.io/@korkje/fifo)!

**Comment by sgwilym** [comment]
Nice, thank you!
